import { decodeInstruction } from './decoder';
import type { MipsInstruction } from '../model/instruction';
import type { RomFunctionEntry } from '../decompiler/romFunctionEntry';
export type RomFunctionCfgOptions = { maxInstructions?: number; byteOrder?: 'big' | 'little' };
export type RomFunctionBasicBlock = { startAddress: number; instructions: MipsInstruction[]; successors: number[] };
export type DecodedRomFunctionCfg = { entry: RomFunctionEntry; blocks: RomFunctionBasicBlock[]; instructionCount: number };
function readWord(bytes: Uint8Array, offset: number, order: 'big' | 'little'): number { if (offset < 0 || offset + 4 > bytes.length) throw new Error(`instruction read at ROM offset 0x${offset.toString(16)} exceeds ROM bounds`); return order === 'big' ? ((bytes[offset]<<24)|(bytes[offset+1]<<16)|(bytes[offset+2]<<8)|bytes[offset+3])>>>0 : ((bytes[offset+3]<<24)|(bytes[offset+2]<<16)|(bytes[offset+1]<<8)|bytes[offset])>>>0; }
const nextAddress=(a:number)=>(a+4)>>>0;
export function decodeRomFunctionCfg(rom:Uint8Array,entry:RomFunctionEntry,options:RomFunctionCfgOptions={}):DecodedRomFunctionCfg { const maxInstructions=options.maxInstructions??4096, order=options.byteOrder??'big'; if(!Number.isInteger(maxInstructions)||maxInstructions<=0) throw new Error('maxInstructions must be a positive integer'); if(!Number.isInteger(entry.romOffset)||entry.romOffset<0||entry.romOffset%4!==0||entry.romOffset>=rom.length) throw new Error('ROM function entry offset must be a valid 4-byte-aligned ROM offset'); const pending=[entry.address>>>0], visited=new Set<number>(), blocks=new Map<number,RomFunctionBasicBlock>(); let instructionCount=0; const romOffsetFor=(a:number)=>entry.romOffset+((a-entry.address)|0); const decodeAt=(a:number)=>{const relative=(a-entry.address)|0, offset=romOffsetFor(a); if(offset<0||offset+4>rom.length||(relative&3)!==0) throw new Error(`CFG target 0x${a.toString(16)} is outside the evidenced ROM function range`); return decodeInstruction(readWord(rom,offset,order),a);}; while(pending.length){const start=pending.pop()!>>>0;if(visited.has(start))continue;visited.add(start);const instructions:MipsInstruction[]=[], successors:number[]=[];let address=start;for(;;){if(instructionCount>=maxInstructions)throw new Error(`function at 0x${entry.address.toString(16)} exceeded the CFG instruction bound`);const instruction=decodeAt(address);instructions.push(instruction);instructionCount++;const after=nextAddress(address);if(instruction.isReturn){const d=decodeAt(after);instructions.push(d);instructionCount++;break;}if(instruction.isConditionalBranch){const d=decodeAt(after);instructions.push(d);instructionCount++;if(instruction.targetAddress===undefined)throw new Error(`CFG branch at 0x${address.toString(16)} has no resolved target`);const target=instruction.targetAddress>>>0,fallthrough=nextAddress(after);if(romOffsetFor(target)<0||romOffsetFor(target)+4>rom.length)throw new Error(`CFG branch at 0x${address.toString(16)} has no resolved target`);successors.push(target,fallthrough);pending.push(fallthrough,target);break;}if(instruction.isJump){const d=decodeAt(after);instructions.push(d);instructionCount++;if(instruction.isCall){const f=nextAddress(after);successors.push(f);pending.push(f);}else if(instruction.targetAddress!==undefined){const target=instruction.targetAddress>>>0;if(romOffsetFor(target)<0||romOffsetFor(target)+4>rom.length)throw new Error(`CFG target 0x${target.toString(16)} is outside the evidenced ROM function range`);successors.push(target);pending.push(target);}break;}address=after;}blocks.set(start,{startAddress:start,instructions,successors:[...new Set(successors)]});}return{entry,blocks:[...blocks.values()].sort((a,b)=>a.startAddress-b.startAddress),instructionCount}; }
