export type CType = 'void' | 'int32_t' | 'uint32_t' | 'float' | 'double' | 'pointer' | 'unknown';
export interface CExpr { kind: 'literal' | 'variable' | 'binary' | 'unary' | 'call' | 'cast'; value?: string | number; op?: string; left?: CExpr; right?: CExpr; operand?: CExpr; callee?: string; args?: CExpr[]; type?: CType; }
export interface CStmt { kind: 'decl' | 'expr' | 'return' | 'if' | 'while' | 'block' | 'break' | 'continue'; name?: string; type?: CType; init?: CExpr; expr?: CExpr; condition?: CExpr; thenBranch?: CStmt; elseBranch?: CStmt; body?: CStmt[]; }
export interface CFunction { kind: 'function'; name: string; returnType: CType; parameters: Array<{ name: string; type: CType }>; body: CStmt[]; }
export interface CProgram { functions: CFunction[]; }
export function renderExpr(expr: CExpr): string { switch (expr.kind) { case 'literal': return String(expr.value ?? '0'); case 'variable': return String(expr.value ?? 'unknown'); case 'binary': return `(${renderExpr(expr.left!)} ${expr.op ?? '?'} ${renderExpr(expr.right!)})`; case 'unary': { const operand = renderExpr(expr.operand!); return expr.op === '!' ? `!${operand}` : `(${expr.op ?? '?'}${operand})`; } case 'call': return `${expr.callee ?? 'unknown'}(${(expr.args ?? []).map(renderExpr).join(', ')})`; case 'cast': return `((${expr.type ?? 'unknown'})${renderExpr(expr.operand!)})`; } }
function flattenBranchStatements(statements: readonly CStmt[]): CStmt[] { const out: CStmt[] = []; for (const s of statements) { if (s.kind === 'block') out.push(...flattenBranchStatements(s.body ?? [])); else out.push(s); } return out; }
export function renderStmt(stmt: CStmt, indent = ''): string { switch (stmt.kind) { case 'decl': return `${indent}${stmt.type ?? 'unknown'} ${stmt.name ?? 'tmp'}${stmt.init ? ` = ${renderExpr(stmt.init)}` : ''};`; case 'expr': return `${indent}${renderExpr(stmt.expr!)};`; case 'return': return `${indent}return${stmt.expr ? ` ${renderExpr(stmt.expr)}` : ''};`; case 'break': return `${indent}break;`; case 'continue': return `${indent}continue;`; case 'if': { const body = (b: CStmt | undefined) => flattenBranchStatements(b?.kind === 'block' ? (b.body ?? []) : b ? [b] : []).map(s => renderStmt(s, `${indent}    `)).join('\n'); const elseText = stmt.elseBranch ? ` else\n${indent}{\n${body(stmt.elseBranch)}\n${indent}}` : ''; return `${indent}if (${renderExpr(stmt.condition! )})\n${indent}{\n${body(stmt.thenBranch)}\n${indent}}${elseText}`; } case 'while': return `${indent}while (${renderExpr(stmt.condition! )})\n${indent}{\n${flattenBranchStatements(stmt.body ?? []).map(s => renderStmt(s, `${indent}    `)).join('\n')}\n${indent}}`; case 'block': return `${indent}{\n${flattenBranchStatements(stmt.body ?? []).map(s => renderStmt(s, `${indent}    `)).join('\n')}\n${indent}}`; } }
export function renderFunction(fn: CFunction): string { const params = fn.parameters.length === 1 && fn.parameters[0].type === 'void' ? 'void' : fn.parameters.length === 0 ? '' : fn.parameters.map(p => `${p.type} ${p.name}`).join(', '); return `${fn.returnType} ${fn.name}(${params})\n{\n${fn.body.map(stmt => renderStmt(stmt, '    ')).join('\n')}\n}`; }
export function renderProgram(program: CProgram): string { return program.functions.map(renderFunction).join('\n\n') + (program.functions.length ? '\n' : ''); }
