import React, { useRef, useEffect, useState } from 'react';
import { MonitorPlay, Play, Pause, RotateCcw, Cpu, Activity, HardDrive, Eye } from 'lucide-react';
import { RomHeader, DecompiledFunction } from '../types/n64';
import { formatHex32 } from '../utils/n64Parser';

interface VirtualExecutionViewProps {
  header: RomHeader | null;
  functions: DecompiledFunction[];
}

export const VirtualExecutionView: React.FC<VirtualExecutionViewProps> = ({ header, functions }) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isRunning, setIsRunning] = useState(true);
  const [frameTick, setFrameTick] = useState(0);
  const [viStatus, setViStatus] = useState(0x0000320e); // NTSC 16-bit color mode
  const [viDramAddr, setViDramAddr] = useState(0x00100000); // 1MB Framebuffer
  const [pc, setPc] = useState(header?.entryPoint || 0x80000400);

  useEffect(() => {
    let animationFrameId: number;
    let rotationAngle = 0;

    const renderVirtualN64Frame = () => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      const width = canvas.width;
      const height = canvas.height;

      // Clear N64 Framebuffer (dark navy blue)
      ctx.fillStyle = '#0a0e17';
      ctx.fillRect(0, 0, width, height);

      // Draw N64 VI CRT scanlines effect
      ctx.fillStyle = 'rgba(0, 255, 255, 0.03)';
      for (let y = 0; y < height; y += 4) {
        ctx.fillRect(0, y, width, 1);
      }

      // Draw Retro N64 3D Spinning Cube / N Logo Simulation
      ctx.save();
      ctx.translate(width / 2, height / 2);

      rotationAngle += 0.03;
      const cosA = Math.cos(rotationAngle);
      const sinA = Math.sin(rotationAngle);

      // 3D Cube vertices
      const cubeSize = 40;
      const vertices = [
        [-cubeSize, -cubeSize, -cubeSize],
        [cubeSize, -cubeSize, -cubeSize],
        [cubeSize, cubeSize, -cubeSize],
        [-cubeSize, cubeSize, -cubeSize],
        [-cubeSize, -cubeSize, cubeSize],
        [cubeSize, -cubeSize, cubeSize],
        [cubeSize, cubeSize, cubeSize],
        [-cubeSize, cubeSize, cubeSize],
      ];

      // Rotate & Project
      const projected = vertices.map(([x, y, z]) => {
        // Rotate around Y
        const rx1 = x * cosA - z * sinA;
        const rz1 = x * sinA + z * cosA;
        // Rotate around X
        const ry2 = y * cosA - rz1 * sinA;
        const rz2 = y * sinA + rz1 * cosA;

        const distance = 160;
        const fov = 200;
        const scale = fov / (distance + rz2);

        return [rx1 * scale, ry2 * scale];
      });

      // Edges
      const edges = [
        [0, 1], [1, 2], [2, 3], [3, 0], // Back
        [4, 5], [5, 6], [6, 7], [7, 4], // Front
        [0, 4], [1, 5], [2, 6], [3, 7], // Connecting
      ];

      ctx.strokeStyle = '#06b6d4'; // Cyan
      ctx.lineWidth = 2;
      ctx.beginPath();
      edges.forEach(([i, j]) => {
        ctx.moveTo(projected[i][0], projected[i][1]);
        ctx.lineTo(projected[j][0], projected[j][1]);
      });
      ctx.stroke();

      // N64 Red / Blue / Green / Yellow accent corners
      const colors = ['#e11d48', '#3b82f6', '#10b981', '#f59e0b'];
      projected.slice(0, 4).forEach(([px, py], idx) => {
        ctx.fillStyle = colors[idx];
        ctx.beginPath();
        ctx.arc(px, py, 4, 0, Math.PI * 2);
        ctx.fill();
      });

      ctx.restore();

      // Draw On-Screen Display (OSD) text generated by VI controller
      ctx.fillStyle = '#f8fafc';
      ctx.font = 'bold 12px monospace';
      ctx.fillText(`N64 VI DISPLAY ENGINE [320x240]`, 12, 22);
      ctx.fillStyle = '#38bdf8';
      ctx.font = '10px monospace';
      ctx.fillText(`TITLE: ${header?.imageName || 'N64_GAME'} [${header?.gameId || 'N64'}]`, 12, 38);
      ctx.fillText(`STATUS: RECOMPILED C++ EXECUTION ACTIVE`, 12, 52);

      if (isRunning) {
        setFrameTick((prev) => prev + 1);
        setPc((prev) => prev + 4);
        animationFrameId = requestAnimationFrame(renderVirtualN64Frame);
      }
    };

    if (isRunning) {
      animationFrameId = requestAnimationFrame(renderVirtualN64Frame);
    }

    return () => cancelAnimationFrame(animationFrameId);
  }, [isRunning, header]);

  return (
    <div className="flex flex-col lg:flex-row h-full bg-slate-950 font-mono text-slate-200 overflow-hidden">
      {/* Frame Buffer Canvas Monitor */}
      <div className="flex-1 flex flex-col items-center justify-center p-6 bg-slate-950 border-r border-slate-800 space-y-4">
        {/* CRT Display Frame */}
        <div className="p-3 bg-slate-900 rounded-xl border-2 border-slate-800 shadow-2xl space-y-2 max-w-lg w-full">
          <div className="flex items-center justify-between text-xs px-2 text-slate-400">
            <span className="flex items-center gap-1.5 font-bold text-slate-300">
              <MonitorPlay size={14} className="text-cyan-400" />
              <span>N64 Video Interface (VI) Screen Buffer</span>
            </span>
            <span className="text-emerald-400 font-mono font-bold">60.0 FPS</span>
          </div>

          <div className="relative aspect-[4/3] bg-black rounded-lg overflow-hidden border border-slate-800 flex items-center justify-center shadow-inner">
            <canvas ref={canvasRef} width={320} height={240} className="w-full h-full object-contain" />
          </div>

          {/* Player Controls */}
          <div className="flex items-center justify-between pt-2 px-1 text-xs">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setIsRunning(!isRunning)}
                className="flex items-center gap-1.5 px-3 py-1.5 bg-cyan-600 hover:bg-cyan-500 text-white font-semibold rounded shadow transition cursor-pointer"
              >
                {isRunning ? <Pause size={13} /> : <Play size={13} />}
                <span>{isRunning ? 'Pause' : 'Resume'}</span>
              </button>

              <button
                onClick={() => {
                  setFrameTick(0);
                  setPc(header?.entryPoint || 0x80000400);
                }}
                className="flex items-center gap-1 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded border border-slate-700 transition cursor-pointer"
              >
                <RotateCcw size={13} />
                <span>Reset</span>
              </button>
            </div>

            <span className="text-slate-500 text-[11px]">Frame Count: {frameTick.toLocaleString()}</span>
          </div>
        </div>
      </div>

      {/* Hardware State & Registers Inspector */}
      <div className="w-full lg:w-80 bg-slate-900 p-5 space-y-5 overflow-y-auto shrink-0 border-t lg:border-t-0 border-slate-800">
        <div className="flex items-center gap-2 text-cyan-400 font-bold text-sm border-b border-slate-800 pb-3">
          <Cpu size={16} />
          <span>Virtual N64 CPU & HW Registers</span>
        </div>

        {/* CPU Registers */}
        <div className="space-y-3">
          <div className="text-xs font-bold text-slate-400 uppercase tracking-wider">MIPS CPU State</div>
          <div className="grid grid-cols-2 gap-2 text-xs font-mono">
            <div className="p-2.5 rounded bg-slate-950 border border-slate-800">
              <div className="text-slate-500 text-[10px]">PC (Program Counter)</div>
              <div className="font-bold text-cyan-300">{formatHex32(pc)}</div>
            </div>

            <div className="p-2.5 rounded bg-slate-950 border border-slate-800">
              <div className="text-slate-500 text-[10px]">$sp (Stack Pointer)</div>
              <div className="font-bold text-slate-200">0x803C0000</div>
            </div>

            <div className="p-2.5 rounded bg-slate-950 border border-slate-800">
              <div className="text-slate-500 text-[10px]">$v0 (Return Val)</div>
              <div className="font-bold text-emerald-400">0x00000001</div>
            </div>

            <div className="p-2.5 rounded bg-slate-950 border border-slate-800">
              <div className="text-slate-500 text-[10px]">$a0 (Arg 0)</div>
              <div className="font-bold text-amber-300">0x00000040</div>
            </div>
          </div>
        </div>

        {/* VI / RSP / DP Hardware Registers */}
        <div className="space-y-3">
          <div className="text-xs font-bold text-slate-400 uppercase tracking-wider">N64 Memory Map MMIO</div>
          <div className="space-y-2 text-xs font-mono">
            <div className="p-2.5 rounded bg-slate-950 border border-slate-800 flex items-center justify-between">
              <div>
                <div className="text-slate-500 text-[10px]">VI_STATUS_REG (0x04400000)</div>
                <div className="font-bold text-purple-300">{formatHex32(viStatus)}</div>
              </div>
              <span className="text-[10px] px-1.5 py-0.5 rounded bg-purple-950 text-purple-300">NTSC 16-bit</span>
            </div>

            <div className="p-2.5 rounded bg-slate-950 border border-slate-800 flex items-center justify-between">
              <div>
                <div className="text-slate-500 text-[10px]">VI_DRAM_ADDR_REG (0x04400004)</div>
                <div className="font-bold text-cyan-300">{formatHex32(viDramAddr)}</div>
              </div>
              <span className="text-[10px] px-1.5 py-0.5 rounded bg-cyan-950 text-cyan-300">1MB FB</span>
            </div>

            <div className="p-2.5 rounded bg-slate-950 border border-slate-800 flex items-center justify-between">
              <div>
                <div className="text-slate-500 text-[10px]">SP_STATUS_REG (0x04000010)</div>
                <div className="font-bold text-emerald-400">0x00000001</div>
              </div>
              <span className="text-[10px] px-1.5 py-0.5 rounded bg-emerald-950 text-emerald-300">RSP Ready</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
